type: object
properties:
  interval:
    $ref: ./enum/EnumApplicationIntervals.yaml
  indexer:
    $ref: ./Indexer.yaml
  customers:
    $ref: ./Customer.yaml
required:
  - interval
  - indexer
  - customers
