type: object
description: Meta informações referente a API requisitada.
properties:
  totalRecords:
    type: integer
    description: Número total de registros no resultado
    example: 1
  totalPages:
    type: integer
    description: Número total de páginas no resultado
    example: 1
required:
  - totalRecords
  - totalPages
